services:
  my-mongo-server:
    image: mongo:latest
    container_name: my-mongo-server
    restart: unless-stopped
    volumes:
      - my-mongo-volume:/data/db
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
volumes:
  my-mongo-volume:
    driver: local